"""initial_tables_with_float_timestamps

Revision ID: 1df7162a1a3e
Revises: 
Create Date: 2025-12-22 11:54:39.769511
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1df7162a1a3e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.String(length=50), nullable=False, comment='坐席业务ID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='显示名称'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='头像URL'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='角色: agent/admin'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: online/busy/break/lunch/training/offline'),
    sa.Column('status_note', sa.String(length=200), nullable=True, comment='状态说明'),
    sa.Column('status_updated_at', sa.Float(), nullable=True, comment='状态更新时间'),
    sa.Column('last_active_at', sa.Float(), nullable=True, comment='最近活跃时间'),
    sa.Column('last_login_at', sa.Float(), nullable=True, comment='最后登录时间'),
    sa.Column('max_sessions', sa.Integer(), nullable=False, comment='最大同时服务会话数'),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='技能标签列表'),
    sa.Column('created_at', sa.Float(), nullable=False, comment='创建时间(Unix时间戳)'),
    sa.Column('updated_at', sa.Float(), nullable=False, comment='更新时间(Unix时间戳)'),
    sa.PrimaryKeyConstraint('id'),
    comment='坐席账号表'
    )
    op.create_index(op.f('ix_agents_agent_id'), 'agents', ['agent_id'], unique=True)
    op.create_index(op.f('ix_agents_role'), 'agents', ['role'], unique=False)
    op.create_index('ix_agents_role_status', 'agents', ['role', 'status'], unique=False)
    op.create_index(op.f('ix_agents_status'), 'agents', ['status'], unique=False)
    op.create_index(op.f('ix_agents_username'), 'agents', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audit_id', sa.String(length=50), nullable=False, comment='审计日志ID'),
    sa.Column('ticket_id', sa.String(length=50), nullable=False, comment='关联工单ID'),
    sa.Column('event_type', sa.String(length=50), nullable=False, comment='事件类型: created/status_changed/assigned/commented/etc'),
    sa.Column('operator_id', sa.String(length=100), nullable=False, comment='操作者ID'),
    sa.Column('operator_name', sa.String(length=100), nullable=True, comment='操作者名称'),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='事件详情'),
    sa.Column('created_at', sa.Float(), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='审计日志表'
    )
    op.create_index(op.f('ix_audit_logs_audit_id'), 'audit_logs', ['audit_id'], unique=True)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index('ix_audit_logs_operator_created', 'audit_logs', ['operator_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_operator_id'), 'audit_logs', ['operator_id'], unique=False)
    op.create_index('ix_audit_logs_ticket_created', 'audit_logs', ['ticket_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_ticket_id'), 'audit_logs', ['ticket_id'], unique=False)
    op.create_table('email_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.String(length=50), nullable=False, comment='记录ID'),
    sa.Column('subject', sa.String(length=500), nullable=False, comment='邮件主题'),
    sa.Column('from_email', sa.String(length=200), nullable=False, comment='发件人邮箱'),
    sa.Column('to_email', sa.String(length=200), nullable=False, comment='收件人邮箱'),
    sa.Column('cc_emails', sa.String(length=1000), nullable=True, comment='抄送邮箱列表(逗号分隔)'),
    sa.Column('bcc_emails', sa.String(length=1000), nullable=True, comment='密送邮箱列表(逗号分隔)'),
    sa.Column('body_text', sa.Text(), nullable=True, comment='纯文本内容'),
    sa.Column('body_html', sa.Text(), nullable=True, comment='HTML内容'),
    sa.Column('email_type', sa.String(length=50), nullable=True, comment='邮件类型: notification/reply/system'),
    sa.Column('template_id', sa.String(length=100), nullable=True, comment='使用的模板ID'),
    sa.Column('session_id', sa.String(length=100), nullable=True, comment='关联会话ID'),
    sa.Column('ticket_id', sa.String(length=50), nullable=True, comment='关联工单ID'),
    sa.Column('customer_id', sa.String(length=100), nullable=True, comment='关联客户ID'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: pending/sent/failed'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='重试次数'),
    sa.Column('external_id', sa.String(length=200), nullable=True, comment='外部服务返回的ID(如 Message-ID)'),
    sa.Column('external_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='外部服务响应详情'),
    sa.Column('created_at', sa.Float(), nullable=False, comment='创建时间'),
    sa.Column('sent_at', sa.Float(), nullable=True, comment='发送时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='邮件发送记录表'
    )
    op.create_index(op.f('ix_email_records_created_at'), 'email_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_email_records_customer_id'), 'email_records', ['customer_id'], unique=False)
    op.create_index(op.f('ix_email_records_email_type'), 'email_records', ['email_type'], unique=False)
    op.create_index(op.f('ix_email_records_record_id'), 'email_records', ['record_id'], unique=True)
    op.create_index(op.f('ix_email_records_session_id'), 'email_records', ['session_id'], unique=False)
    op.create_index(op.f('ix_email_records_status'), 'email_records', ['status'], unique=False)
    op.create_index('ix_email_records_status_created', 'email_records', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_email_records_ticket_id'), 'email_records', ['ticket_id'], unique=False)
    op.create_index('ix_email_records_to_created', 'email_records', ['to_email', 'created_at'], unique=False)
    op.create_index(op.f('ix_email_records_to_email'), 'email_records', ['to_email'], unique=False)
    op.create_table('session_archives',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('archive_id', sa.String(length=50), nullable=False, comment='归档ID'),
    sa.Column('session_id', sa.String(length=100), nullable=False, comment='原会话ID'),
    sa.Column('session_name', sa.String(length=200), nullable=True, comment='会话名称/标题'),
    sa.Column('customer_id', sa.String(length=100), nullable=True, comment='客户ID'),
    sa.Column('customer_email', sa.String(length=200), nullable=True, comment='客户邮箱'),
    sa.Column('customer_name', sa.String(length=100), nullable=True, comment='客户名称'),
    sa.Column('agent_id', sa.String(length=100), nullable=True, comment='处理坐席ID'),
    sa.Column('agent_name', sa.String(length=100), nullable=True, comment='处理坐席名称'),
    sa.Column('channel', sa.String(length=50), nullable=True, comment='会话渠道: web/email/chat'),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='消息列表'),
    sa.Column('message_count', sa.Integer(), nullable=True, comment='消息数量'),
    sa.Column('duration_seconds', sa.Integer(), nullable=True, comment='会话时长(秒)'),
    sa.Column('ticket_id', sa.String(length=50), nullable=True, comment='关联工单ID'),
    sa.Column('started_at', sa.Float(), nullable=True, comment='会话开始时间'),
    sa.Column('ended_at', sa.Float(), nullable=True, comment='会话结束时间'),
    sa.Column('archived_at', sa.Float(), nullable=False, comment='归档时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='会话归档表'
    )
    op.create_index('ix_session_archives_agent_archived', 'session_archives', ['agent_id', 'archived_at'], unique=False)
    op.create_index(op.f('ix_session_archives_agent_id'), 'session_archives', ['agent_id'], unique=False)
    op.create_index(op.f('ix_session_archives_archive_id'), 'session_archives', ['archive_id'], unique=True)
    op.create_index(op.f('ix_session_archives_archived_at'), 'session_archives', ['archived_at'], unique=False)
    op.create_index(op.f('ix_session_archives_channel'), 'session_archives', ['channel'], unique=False)
    op.create_index('ix_session_archives_customer_archived', 'session_archives', ['customer_id', 'archived_at'], unique=False)
    op.create_index(op.f('ix_session_archives_customer_email'), 'session_archives', ['customer_email'], unique=False)
    op.create_index(op.f('ix_session_archives_customer_id'), 'session_archives', ['customer_id'], unique=False)
    op.create_index(op.f('ix_session_archives_session_id'), 'session_archives', ['session_id'], unique=False)
    op.create_index(op.f('ix_session_archives_ticket_id'), 'session_archives', ['ticket_id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.String(length=50), nullable=False, comment='工单号'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='工单标题'),
    sa.Column('description', sa.Text(), nullable=False, comment='工单描述'),
    sa.Column('session_name', sa.String(length=100), nullable=True, comment='关联会话ID'),
    sa.Column('ticket_type', sa.String(length=20), nullable=False, comment='工单类型'),
    sa.Column('status', sa.String(length=30), nullable=False, comment='工单状态'),
    sa.Column('priority', sa.String(length=20), nullable=False, comment='优先级'),
    sa.Column('created_by', sa.String(length=100), nullable=False, comment='创建者ID'),
    sa.Column('created_by_name', sa.String(length=100), nullable=True, comment='创建者名称'),
    sa.Column('assigned_agent_id', sa.String(length=100), nullable=True, comment='指派坐席ID'),
    sa.Column('assigned_agent_name', sa.String(length=100), nullable=True, comment='指派坐席名称'),
    sa.Column('customer', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='客户信息'),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='扩展元数据'),
    sa.Column('closed_at', sa.Float(), nullable=True, comment='关闭时间'),
    sa.Column('archived_at', sa.Float(), nullable=True, comment='归档时间'),
    sa.Column('first_response_at', sa.Float(), nullable=True, comment='首次响应时间'),
    sa.Column('resolved_at', sa.Float(), nullable=True, comment='解决时间'),
    sa.Column('reopened_at', sa.Float(), nullable=True, comment='重新打开时间'),
    sa.Column('reopened_count', sa.Integer(), nullable=False, comment='重新打开次数'),
    sa.Column('reopened_by', sa.String(length=100), nullable=True, comment='重新打开者'),
    sa.Column('created_at', sa.Float(), nullable=False, comment='创建时间(Unix时间戳)'),
    sa.Column('updated_at', sa.Float(), nullable=False, comment='更新时间(Unix时间戳)'),
    sa.PrimaryKeyConstraint('id'),
    comment='工单主表'
    )
    op.create_index(op.f('ix_tickets_assigned_agent_id'), 'tickets', ['assigned_agent_id'], unique=False)
    op.create_index('ix_tickets_created_at', 'tickets', ['created_at'], unique=False)
    op.create_index(op.f('ix_tickets_created_by'), 'tickets', ['created_by'], unique=False)
    op.create_index(op.f('ix_tickets_priority'), 'tickets', ['priority'], unique=False)
    op.create_index(op.f('ix_tickets_session_name'), 'tickets', ['session_name'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_index('ix_tickets_status_priority', 'tickets', ['status', 'priority'], unique=False)
    op.create_index(op.f('ix_tickets_ticket_id'), 'tickets', ['ticket_id'], unique=True)
    op.create_table('ticket_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.String(length=50), nullable=False),
    sa.Column('agent_id', sa.String(length=100), nullable=True, comment='指派坐席ID'),
    sa.Column('agent_name', sa.String(length=100), nullable=True, comment='指派坐席名称'),
    sa.Column('assigned_by', sa.String(length=100), nullable=True, comment='指派者'),
    sa.Column('note', sa.Text(), nullable=True, comment='指派备注'),
    sa.Column('assigned_at', sa.Float(), nullable=False, comment='指派时间'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.ticket_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='工单指派历史表'
    )
    op.create_index(op.f('ix_ticket_assignments_agent_id'), 'ticket_assignments', ['agent_id'], unique=False)
    op.create_index('ix_ticket_assignments_assigned_at', 'ticket_assignments', ['assigned_at'], unique=False)
    op.create_index(op.f('ix_ticket_assignments_ticket_id'), 'ticket_assignments', ['ticket_id'], unique=False)
    op.create_table('ticket_attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attachment_id', sa.String(length=50), nullable=False, comment='附件ID'),
    sa.Column('ticket_id', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False, comment='文件名'),
    sa.Column('stored_path', sa.String(length=1000), nullable=False, comment='存储路径'),
    sa.Column('content_type', sa.String(length=100), nullable=True, comment='MIME类型'),
    sa.Column('size', sa.Integer(), nullable=False, comment='文件大小(字节)'),
    sa.Column('comment_type', sa.String(length=20), nullable=False, comment='附件类型: internal/public'),
    sa.Column('uploader_id', sa.String(length=100), nullable=False, comment='上传者ID'),
    sa.Column('uploader_name', sa.String(length=100), nullable=True, comment='上传者名称'),
    sa.Column('created_at', sa.Float(), nullable=False, comment='创建时间(Unix时间戳)'),
    sa.Column('updated_at', sa.Float(), nullable=False, comment='更新时间(Unix时间戳)'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.ticket_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='工单附件表'
    )
    op.create_index(op.f('ix_ticket_attachments_attachment_id'), 'ticket_attachments', ['attachment_id'], unique=True)
    op.create_index(op.f('ix_ticket_attachments_ticket_id'), 'ticket_attachments', ['ticket_id'], unique=False)
    op.create_table('ticket_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comment_id', sa.String(length=50), nullable=False, comment='评论ID'),
    sa.Column('ticket_id', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False, comment='评论内容'),
    sa.Column('author_id', sa.String(length=100), nullable=False, comment='作者ID'),
    sa.Column('author_name', sa.String(length=100), nullable=True, comment='作者名称'),
    sa.Column('comment_type', sa.String(length=20), nullable=False, comment='评论类型: internal/public'),
    sa.Column('mentions', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='提及的用户列表'),
    sa.Column('created_at', sa.Float(), nullable=False, comment='创建时间(Unix时间戳)'),
    sa.Column('updated_at', sa.Float(), nullable=False, comment='更新时间(Unix时间戳)'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.ticket_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='工单评论表'
    )
    op.create_index(op.f('ix_ticket_comments_author_id'), 'ticket_comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_ticket_comments_comment_id'), 'ticket_comments', ['comment_id'], unique=True)
    op.create_index('ix_ticket_comments_created_at', 'ticket_comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_ticket_comments_ticket_id'), 'ticket_comments', ['ticket_id'], unique=False)
    op.create_table('ticket_status_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('history_id', sa.String(length=50), nullable=False, comment='历史记录ID'),
    sa.Column('ticket_id', sa.String(length=50), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True, comment='原状态'),
    sa.Column('to_status', sa.String(length=30), nullable=False, comment='新状态'),
    sa.Column('changed_by', sa.String(length=100), nullable=False, comment='变更者'),
    sa.Column('change_reason', sa.String(length=500), nullable=True, comment='变更原因'),
    sa.Column('comment', sa.Text(), nullable=True, comment='备注'),
    sa.Column('changed_at', sa.Float(), nullable=False, comment='变更时间'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.ticket_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='工单状态历史表'
    )
    op.create_index('ix_ticket_status_history_changed_at', 'ticket_status_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_ticket_status_history_history_id'), 'ticket_status_history', ['history_id'], unique=True)
    op.create_index(op.f('ix_ticket_status_history_ticket_id'), 'ticket_status_history', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_status_history_ticket_id'), table_name='ticket_status_history')
    op.drop_index(op.f('ix_ticket_status_history_history_id'), table_name='ticket_status_history')
    op.drop_index('ix_ticket_status_history_changed_at', table_name='ticket_status_history')
    op.drop_table('ticket_status_history')
    op.drop_index(op.f('ix_ticket_comments_ticket_id'), table_name='ticket_comments')
    op.drop_index('ix_ticket_comments_created_at', table_name='ticket_comments')
    op.drop_index(op.f('ix_ticket_comments_comment_id'), table_name='ticket_comments')
    op.drop_index(op.f('ix_ticket_comments_author_id'), table_name='ticket_comments')
    op.drop_table('ticket_comments')
    op.drop_index(op.f('ix_ticket_attachments_ticket_id'), table_name='ticket_attachments')
    op.drop_index(op.f('ix_ticket_attachments_attachment_id'), table_name='ticket_attachments')
    op.drop_table('ticket_attachments')
    op.drop_index(op.f('ix_ticket_assignments_ticket_id'), table_name='ticket_assignments')
    op.drop_index('ix_ticket_assignments_assigned_at', table_name='ticket_assignments')
    op.drop_index(op.f('ix_ticket_assignments_agent_id'), table_name='ticket_assignments')
    op.drop_table('ticket_assignments')
    op.drop_index(op.f('ix_tickets_ticket_id'), table_name='tickets')
    op.drop_index('ix_tickets_status_priority', table_name='tickets')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_session_name'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_priority'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_created_by'), table_name='tickets')
    op.drop_index('ix_tickets_created_at', table_name='tickets')
    op.drop_index(op.f('ix_tickets_assigned_agent_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_session_archives_ticket_id'), table_name='session_archives')
    op.drop_index(op.f('ix_session_archives_session_id'), table_name='session_archives')
    op.drop_index(op.f('ix_session_archives_customer_id'), table_name='session_archives')
    op.drop_index(op.f('ix_session_archives_customer_email'), table_name='session_archives')
    op.drop_index('ix_session_archives_customer_archived', table_name='session_archives')
    op.drop_index(op.f('ix_session_archives_channel'), table_name='session_archives')
    op.drop_index(op.f('ix_session_archives_archived_at'), table_name='session_archives')
    op.drop_index(op.f('ix_session_archives_archive_id'), table_name='session_archives')
    op.drop_index(op.f('ix_session_archives_agent_id'), table_name='session_archives')
    op.drop_index('ix_session_archives_agent_archived', table_name='session_archives')
    op.drop_table('session_archives')
    op.drop_index(op.f('ix_email_records_to_email'), table_name='email_records')
    op.drop_index('ix_email_records_to_created', table_name='email_records')
    op.drop_index(op.f('ix_email_records_ticket_id'), table_name='email_records')
    op.drop_index('ix_email_records_status_created', table_name='email_records')
    op.drop_index(op.f('ix_email_records_status'), table_name='email_records')
    op.drop_index(op.f('ix_email_records_session_id'), table_name='email_records')
    op.drop_index(op.f('ix_email_records_record_id'), table_name='email_records')
    op.drop_index(op.f('ix_email_records_email_type'), table_name='email_records')
    op.drop_index(op.f('ix_email_records_customer_id'), table_name='email_records')
    op.drop_index(op.f('ix_email_records_created_at'), table_name='email_records')
    op.drop_table('email_records')
    op.drop_index(op.f('ix_audit_logs_ticket_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_ticket_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_operator_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_operator_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_audit_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_agents_username'), table_name='agents')
    op.drop_index(op.f('ix_agents_status'), table_name='agents')
    op.drop_index('ix_agents_role_status', table_name='agents')
    op.drop_index(op.f('ix_agents_role'), table_name='agents')
    op.drop_index(op.f('ix_agents_agent_id'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
