openapi: 3.0.0
info:
  title: Fiido Shopify 多站点订单查询
  version: 4.0.0
  description: |
    用于查询 Fiido 所有 Shopify 店铺的订单和物流信息。

    ## 特点
    - 全自动站点识别，用户无需指定站点
    - 根据订单号前缀自动识别：UK、DE、EU、FR、IT、ES、NL、PL
    - 邮箱查询自动遍历所有站点

    ## 支持的站点（9个）
    - US (美国站), UK (英国站), EU (欧洲站)
    - DE (德国站), FR (法国站), IT (意大利站)
    - ES (西班牙站), NL (荷兰站), PL (波兰站)

    ## v4.0.0 更新（重要！）
    - **新增 delivery_status 字段**：商品送达状态（success/in_transit/returned/refunded等）
    - **新增 delivery_status_zh 字段**：商品状态中文翻译（已收货/运输中/已退款等）
    - **新增 delivery_status_en 字段**：商品状态英文翻译（Received/In Transit/Refunded等）
    - **新增商品级物流字段**：tracking_company, tracking_number, tracking_url
    - AI 回复时必须直接使用 delivery_status_zh/en 字段，不要自行判断状态！

    ## v3.0.0 更新
    - 从UK单站点升级为全站点自动识别（9个站点）
    - line_items 包含 image_url 字段（商品图片 CDN URL）
    - line_items 包含 product_url 字段（商品详情页链接）
    - line_items 包含 fulfillment_status 字段（商品级别发货状态）

    ## 注意事项
    - 此版本已展开所有 $ref 引用，以兼容 Coze 平台
    - 所有字段类型均与后端 API 实际返回匹配

servers:
  - url: https://ai.fiido.com
    description: Fiido 智能客服 API

paths:
  /api/shopify/orders/global-search:
    get:
      operationId: searchOrderByNumber
      summary: 按订单号搜索订单
      description: |
        根据订单号自动识别站点并搜索订单详情。
        - 自动识别订单号前缀：UK、DE、EU、FR、IT、ES、NL、PL
        - 无前缀订单号会遍历所有站点查找
        - 返回订单完整信息包括商品、地址、物流
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
          description: 订单号关键词（如 UK22080、DE10019）
          example: "UK22080"
      responses:
        '200':
          description: 订单详情
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: 请求是否成功
                  data:
                    type: object
                    properties:
                      order:
                        type: object
                        nullable: true
                        description: 订单详情对象，未找到时为 null
                        properties:
                          order_id:
                            type: string
                            description: Shopify 订单 ID（用于查询物流）
                          order_number:
                            type: string
                            description: 订单号（如 #UK22080）
                          site_code:
                            type: string
                            description: 站点代码（uk/de/eu/fr/it/es/nl/pl/us）
                          created_at:
                            type: string
                            description: 下单时间
                          financial_status:
                            type: string
                            description: 支付状态（paid/pending/refunded）
                          fulfillment_status:
                            type: string
                            description: 发货状态（fulfilled/partial/null）
                          total_price:
                            type: string
                            description: 订单总金额
                          currency:
                            type: string
                            description: 货币代码（GBP/EUR/USD）
                          items_count:
                            type: integer
                            description: 商品数量
                          customer_email:
                            type: string
                            description: 客户邮箱
                          customer_name:
                            type: string
                            description: 客户姓名
                          subtotal_price:
                            type: string
                            description: 商品小计
                          total_shipping:
                            type: string
                            description: 运费
                          total_discounts:
                            type: string
                            description: 折扣金额
                          total_tax:
                            type: string
                            description: 税费
                          note:
                            type: string
                            description: 订单备注
                          tags:
                            type: string
                            description: 订单标签
                          discount_codes:
                            type: array
                            description: 使用的优惠码
                            items:
                              type: string
                          line_items:
                            type: array
                            description: 商品列表
                            items:
                              type: object
                              properties:
                                title:
                                  type: string
                                  description: 商品名称
                                variant_title:
                                  type: string
                                  description: 规格
                                sku:
                                  type: string
                                  description: SKU
                                quantity:
                                  type: integer
                                  description: 数量
                                price:
                                  type: string
                                  description: 单价
                                fulfillment_status:
                                  type: string
                                  description: 商品级别发货状态（fulfilled/null/service）
                                delivery_status:
                                  type: string
                                  description: 商品送达/退款状态（success/in_transit/returned/refunded/cancelled/active/expired等）
                                delivery_status_zh:
                                  type: string
                                  description: 商品状态中文翻译（已收货/运输中/已退款/已退货退款/已取消/已生效/已失效等）- AI回复时必须直接使用此字段！
                                delivery_status_en:
                                  type: string
                                  description: 商品状态英文翻译（Received/In Transit/Refunded/Returned & Refunded/Cancelled/Active/Expired等）- AI回复时必须直接使用此字段！
                                tracking_company:
                                  type: string
                                  description: 承运商（商品级别）
                                tracking_number:
                                  type: string
                                  description: 运单号（商品级别）
                                tracking_url:
                                  type: string
                                  description: 物流追踪链接（商品级别）
                                image_url:
                                  type: string
                                  description: 商品图片 URL（Shopify CDN）
                                product_url:
                                  type: string
                                  description: 商品详情页 URL
                          shipping_address:
                            type: object
                            description: 收货地址
                            properties:
                              address1:
                                type: string
                              address2:
                                type: string
                              city:
                                type: string
                              province:
                                type: string
                              country:
                                type: string
                              zip:
                                type: string
                          fulfillments:
                            type: array
                            description: 发货记录
                            items:
                              type: object
                              properties:
                                id:
                                  type: integer
                                  description: 发货记录ID
                                status:
                                  type: string
                                  description: 发货状态
                                tracking_company:
                                  type: string
                                  description: 承运商
                                tracking_number:
                                  type: string
                                  description: 运单号
                                tracking_url:
                                  type: string
                                  description: 追踪链接
                                created_at:
                                  type: string
                                  description: 发货时间
                                line_items:
                                  type: array
                                  description: 该发货记录包含的商品
                                  items:
                                    type: object
                                    properties:
                                      title:
                                        type: string
                                      quantity:
                                        type: integer
                      cached:
                        type: boolean
                        description: 是否来自缓存
                      cache_ttl:
                        type: integer
                        description: 缓存有效期（秒）

  /api/shopify/orders/global-email-search:
    get:
      operationId: getOrdersByEmail
      summary: 按客户邮箱查询订单列表
      description: |
        根据客户邮箱自动搜索所有站点的订单。
        - 自动遍历所有 9 个站点
        - 汇总该邮箱在各站点的所有订单
        - 按下单时间倒序排列
      parameters:
        - name: email
          in: query
          required: true
          schema:
            type: string
          description: 客户邮箱地址
          example: "customer@example.com"
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 10
          description: 返回订单数量限制（默认10）
      responses:
        '200':
          description: 订单列表
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      orders:
                        type: array
                        description: 订单列表
                        items:
                          type: object
                          properties:
                            order_id:
                              type: string
                              description: Shopify 订单 ID
                            order_number:
                              type: string
                              description: 订单号
                            site_code:
                              type: string
                              description: 站点代码
                            created_at:
                              type: string
                              description: 下单时间
                            financial_status:
                              type: string
                              description: 支付状态
                            fulfillment_status:
                              type: string
                              description: 发货状态
                            total_price:
                              type: string
                              description: 订单总金额
                            currency:
                              type: string
                              description: 货币代码
                            items_count:
                              type: integer
                              description: 商品数量
                            customer_email:
                              type: string
                              description: 客户邮箱
                            customer_name:
                              type: string
                              description: 客户姓名
                            primary_product:
                              type: object
                              description: 主商品信息（用于图文展示）
                              properties:
                                title:
                                  type: string
                                  description: 主商品名称
                                image_url:
                                  type: string
                                  description: 主商品图片 URL
                                product_url:
                                  type: string
                                  description: 主商品详情页 URL
                      total:
                        type: integer
                        description: 总订单数
                      email:
                        type: string
                        description: 查询的邮箱
                      sites_searched:
                        type: array
                        description: 已搜索的站点列表
                        items:
                          type: string
                      sites_with_orders:
                        type: array
                        description: 有订单的站点列表
                        items:
                          type: string

  /api/shopify/tracking:
    get:
      operationId: getOrderTracking
      summary: 获取订单物流追踪信息
      description: |
        获取订单的物流追踪信息。
        - 需要使用 order_id（从订单查询结果中获取）
        - 返回承运商、运单号、追踪链接
        - 返回中英文状态翻译和客服话术模板
      parameters:
        - name: order_id
          in: query
          required: false
          schema:
            type: string
          description: Shopify 订单 ID（数字格式，如 6615015620909）
          example: "6615015620909"
      responses:
        '200':
          description: 物流信息
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      tracking:
                        type: object
                        nullable: true
                        description: 物流追踪信息，无物流时为 null
                        properties:
                          order_id:
                            type: string
                            description: 订单ID
                          order_number:
                            type: string
                            description: 订单号
                          site_code:
                            type: string
                            description: 站点代码
                          fulfillment_status:
                            type: string
                            description: 发货状态
                          fulfillment_status_zh:
                            type: string
                            description: 发货状态（中文）
                          fulfillment_status_en:
                            type: string
                            description: 发货状态（英文）
                          primary_tracking:
                            type: object
                            description: 主要物流信息
                            properties:
                              company:
                                type: string
                                description: 承运商
                              company_normalized:
                                type: string
                                description: 标准化承运商名称
                              number:
                                type: string
                                description: 运单号
                              url:
                                type: string
                                description: 追踪链接
                              status:
                                type: string
                                description: 物流状态
                              status_zh:
                                type: string
                                description: 物流状态（中文）
                              status_en:
                                type: string
                                description: 物流状态（英文）
                              shipped_at:
                                type: string
                                description: 发货时间
                          fulfillments:
                            type: array
                            description: 所有发货记录
                            items:
                              type: object
                              properties:
                                id:
                                  type: integer
                                status:
                                  type: string
                                tracking_company:
                                  type: string
                                tracking_number:
                                  type: string
                                tracking_url:
                                  type: string
                                created_at:
                                  type: string
                                line_items:
                                  type: array
                                  description: 该发货记录包含的商品
                                  items:
                                    type: object
                                    properties:
                                      title:
                                        type: string
                                      quantity:
                                        type: integer
                          message_template_zh:
                            type: string
                            description: 中文客服话术模板
                          message_template_en:
                            type: string
                            description: 英文客服话术模板
                      cached:
                        type: boolean
                      cache_ttl:
                        type: integer
