openapi: 3.0.0
info:
  title: Fiido UK Shopify 订单查询
  version: 1.0.0
  description: |
    用于查询 Fiido UK Shopify 店铺的订单和物流信息。

    ## 功能列表
    - 按客户邮箱查询订单列表
    - 按订单号搜索订单详情
    - 获取订单物流追踪信息
    - 获取订单数量统计

    ## 使用说明
    1. 当用户询问订单状态时，先尝试提取订单号
    2. 如果没有订单号，询问用户的邮箱
    3. 查询结果包含中英文翻译和客服话术模板

servers:
  - url: http://223.4.251.97/ai
    description: 生产环境 (阿里云ECS)
  - url: http://localhost:8000
    description: 本地开发环境

paths:
  /api/shopify/orders/search:
    get:
      operationId: searchOrderByNumber
      summary: 按订单号搜索订单
      description: |
        根据订单号搜索订单详情。
        支持 #UK22080 或 UK22080 格式的订单号。
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
            minLength: 3
          description: 订单号关键词（如 UK22080 或 #UK22080）
          example: "UK22080"
      responses:
        '200':
          description: 订单详情
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderSearchResponse'
        '404':
          description: 订单不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/shopify/orders:
    get:
      operationId: getOrdersByEmail
      summary: 按客户邮箱查询订单列表
      description: 根据客户邮箱查询所有订单记录
      parameters:
        - name: email
          in: query
          required: true
          schema:
            type: string
            format: email
          description: 客户邮箱地址
          example: "customer@example.com"
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 50
            default: 10
          description: 返回订单数量限制
        - name: status
          in: query
          required: false
          schema:
            type: string
            enum: [open, closed, cancelled, any]
            default: any
          description: 订单状态筛选
      responses:
        '200':
          description: 订单列表
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderListResponse'

  /api/shopify/orders/{order_id}/tracking:
    get:
      operationId: getOrderTracking
      summary: 获取订单物流信息
      description: |
        获取订单的物流追踪信息。
        返回结果包含：
        - 承运商信息
        - 运单号
        - 追踪链接
        - 状态中英文翻译
        - 客服话术模板
      parameters:
        - name: order_id
          in: path
          required: true
          schema:
            type: string
          description: Shopify 订单 ID（数字格式）
          example: "6615015620909"
      responses:
        '200':
          description: 物流信息
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrackingResponse'
        '404':
          description: 订单不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/shopify/orders/{order_id}:
    get:
      operationId: getOrderDetail
      summary: 获取订单详情
      description: 获取订单的完整详细信息
      parameters:
        - name: order_id
          in: path
          required: true
          schema:
            type: string
          description: Shopify 订单 ID
      responses:
        '200':
          description: 订单详情
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderDetailResponse'
        '404':
          description: 订单不存在

  /api/shopify/orders/count:
    get:
      operationId: getOrderCount
      summary: 获取订单数量统计
      parameters:
        - name: status
          in: query
          required: false
          schema:
            type: string
            enum: [open, closed, cancelled, any]
            default: any
          description: 订单状态筛选
      responses:
        '200':
          description: 订单数量
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountResponse'

  /api/shopify/health:
    get:
      operationId: healthCheck
      summary: 健康检查
      description: 检查 Shopify API 连接状态
      responses:
        '200':
          description: 健康状态
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

components:
  schemas:
    OrderSearchResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          type: object
          properties:
            order:
              $ref: '#/components/schemas/OrderDetail'
            cached:
              type: boolean
              description: 是否来自缓存
            cache_ttl:
              type: integer
              description: 缓存有效期（秒）

    OrderListResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: object
          properties:
            orders:
              type: array
              items:
                $ref: '#/components/schemas/OrderSummary'
            total:
              type: integer
              description: 总订单数
            cached:
              type: boolean
            cache_ttl:
              type: integer

    OrderDetailResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: object
          properties:
            order:
              $ref: '#/components/schemas/OrderDetail'
            cached:
              type: boolean
            cache_ttl:
              type: integer

    TrackingResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: object
          properties:
            tracking:
              $ref: '#/components/schemas/TrackingInfo'
            cached:
              type: boolean
            cache_ttl:
              type: integer

    CountResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: object
          properties:
            count:
              type: integer
              description: 订单数量
            status:
              type: string
            cached:
              type: boolean
            cache_ttl:
              type: integer

    HealthResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: object
          properties:
            api:
              type: object
              properties:
                status:
                  type: string
                  enum: [healthy, unhealthy]
                shop_domain:
                  type: string
                total_orders:
                  type: integer
            cache:
              type: object
              properties:
                total:
                  type: integer

    OrderSummary:
      type: object
      description: 订单摘要
      properties:
        order_id:
          type: string
          description: Shopify 订单 ID
        order_number:
          type: string
          description: 订单号（如 #UK22080）
        created_at:
          type: string
          description: 下单时间
        financial_status:
          type: string
          description: 支付状态
        fulfillment_status:
          type: string
          nullable: true
          description: 发货状态
        total_price:
          type: string
          description: 订单总金额
        currency:
          type: string
          description: 货币代码
        items_count:
          type: integer
          description: 商品数量
        customer_email:
          type: string
          nullable: true
        customer_name:
          type: string
          nullable: true

    OrderDetail:
      allOf:
        - $ref: '#/components/schemas/OrderSummary'
        - type: object
          properties:
            line_items:
              type: array
              items:
                $ref: '#/components/schemas/LineItem'
            subtotal_price:
              type: string
            total_shipping:
              type: string
            total_discounts:
              type: string
            total_tax:
              type: string
            shipping_address:
              $ref: '#/components/schemas/ShippingAddress'
            fulfillments:
              type: array
              items:
                $ref: '#/components/schemas/Fulfillment'
            note:
              type: string
              nullable: true
            tags:
              type: string
              nullable: true
            discount_codes:
              type: array
              items:
                type: string

    LineItem:
      type: object
      properties:
        title:
          type: string
          description: 商品名称
        variant_title:
          type: string
          nullable: true
          description: 规格
        sku:
          type: string
          nullable: true
        quantity:
          type: integer
        price:
          type: string

    ShippingAddress:
      type: object
      properties:
        address1:
          type: string
        address2:
          type: string
          nullable: true
        city:
          type: string
        province:
          type: string
        country:
          type: string
        zip:
          type: string

    Fulfillment:
      type: object
      properties:
        id:
          type: integer
        status:
          type: string
        tracking_company:
          type: string
          nullable: true
        tracking_number:
          type: string
          nullable: true
        tracking_url:
          type: string
          nullable: true
        created_at:
          type: string

    TrackingInfo:
      type: object
      properties:
        order_id:
          type: string
        order_number:
          type: string
        fulfillment_status:
          type: string
          nullable: true
        fulfillment_status_zh:
          type: string
          description: 发货状态中文
        fulfillment_status_en:
          type: string
          description: 发货状态英文
        fulfillments:
          type: array
          items:
            $ref: '#/components/schemas/Fulfillment'
        primary_tracking:
          type: object
          nullable: true
          properties:
            company:
              type: string
              description: 承运商
            company_normalized:
              type: string
              description: 标准化承运商名称
            number:
              type: string
              description: 运单号
            url:
              type: string
              nullable: true
            tracking_url_generated:
              type: string
              description: 生成的追踪链接
            status:
              type: string
            status_zh:
              type: string
            status_en:
              type: string
            shipped_at:
              type: string
        message_template_zh:
          type: string
          description: 中文客服话术模板
        message_template_en:
          type: string
          description: 英文客服话术模板

    ErrorResponse:
      type: object
      properties:
        detail:
          type: string
          description: 错误详情
